/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	hbasev1 "github.com/HenryGits/hbase-operator/apis/hbase/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHbases implements HbaseInterface
type FakeHbases struct {
	Fake *FakeHbaseV1
	ns   string
}

var hbasesResource = schema.GroupVersionResource{Group: "hbase.dameng.com", Version: "v1", Resource: "hbases"}

var hbasesKind = schema.GroupVersionKind{Group: "hbase.dameng.com", Version: "v1", Kind: "Hbase"}

// Get takes name of the hbase, and returns the corresponding hbase object, and an error if there is any.
func (c *FakeHbases) Get(ctx context.Context, name string, options v1.GetOptions) (result *hbasev1.Hbase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hbasesResource, c.ns, name), &hbasev1.Hbase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hbasev1.Hbase), err
}

// List takes label and field selectors, and returns the list of Hbases that match those selectors.
func (c *FakeHbases) List(ctx context.Context, opts v1.ListOptions) (result *hbasev1.HbaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hbasesResource, hbasesKind, c.ns, opts), &hbasev1.HbaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &hbasev1.HbaseList{ListMeta: obj.(*hbasev1.HbaseList).ListMeta}
	for _, item := range obj.(*hbasev1.HbaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hbases.
func (c *FakeHbases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hbasesResource, c.ns, opts))

}

// Create takes the representation of a hbase and creates it.  Returns the server's representation of the hbase, and an error, if there is any.
func (c *FakeHbases) Create(ctx context.Context, hbase *hbasev1.Hbase, opts v1.CreateOptions) (result *hbasev1.Hbase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hbasesResource, c.ns, hbase), &hbasev1.Hbase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hbasev1.Hbase), err
}

// Update takes the representation of a hbase and updates it. Returns the server's representation of the hbase, and an error, if there is any.
func (c *FakeHbases) Update(ctx context.Context, hbase *hbasev1.Hbase, opts v1.UpdateOptions) (result *hbasev1.Hbase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hbasesResource, c.ns, hbase), &hbasev1.Hbase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hbasev1.Hbase), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHbases) UpdateStatus(ctx context.Context, hbase *hbasev1.Hbase, opts v1.UpdateOptions) (*hbasev1.Hbase, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hbasesResource, "status", c.ns, hbase), &hbasev1.Hbase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hbasev1.Hbase), err
}

// Delete takes name of the hbase and deletes it. Returns an error if one occurs.
func (c *FakeHbases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hbasesResource, c.ns, name), &hbasev1.Hbase{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHbases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hbasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &hbasev1.HbaseList{})
	return err
}

// Patch applies the patch and returns the patched hbase.
func (c *FakeHbases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hbasev1.Hbase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hbasesResource, c.ns, name, pt, data, subresources...), &hbasev1.Hbase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*hbasev1.Hbase), err
}
