# permissions for end users to edit hbases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hbase-editor-role
rules:
- apiGroups:
  - hbase.dameng.com
  resources:
  - hbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hbase.dameng.com
  resources:
  - hbases/status
  verbs:
  - get
