
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hbase.dameng.com
  resources:
  - hbases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hbase.dameng.com
  resources:
  - hbases/finalizers
  verbs:
  - update
- apiGroups:
  - hbase.dameng.com
  resources:
  - hbases/status
  verbs:
  - get
  - patch
  - update
