/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	hbasev1 "github.com/HenryGits/hbase-operator/apis/hbase/v1"
	versioned "github.com/HenryGits/hbase-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/HenryGits/hbase-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/HenryGits/hbase-operator/pkg/client/listers/hbase/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HbaseInformer provides access to a shared informer and lister for
// Hbases.
type HbaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HbaseLister
}

type hbaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHbaseInformer constructs a new informer for Hbase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHbaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHbaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHbaseInformer constructs a new informer for Hbase type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHbaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HbaseV1().Hbases(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HbaseV1().Hbases(namespace).Watch(context.TODO(), options)
			},
		},
		&hbasev1.Hbase{},
		resyncPeriod,
		indexers,
	)
}

func (f *hbaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHbaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hbaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hbasev1.Hbase{}, f.defaultInformer)
}

func (f *hbaseInformer) Lister() v1.HbaseLister {
	return v1.NewHbaseLister(f.Informer().GetIndexer())
}
