---
apiVersion: hbase.dameng.com/v1
kind: Hbase
metadata:
  name: hbase-sample
  namespace: system
spec:
  image:
    repository: hbase
    tag: v2.4.6
  master:
    replicas: 2
  regionServer:
    replicas: 2
  thriftServer:
    name: thrift
    replicas: 1
