/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/HenryGits/hbase-operator/apis/hbase/v1"
	scheme "github.com/HenryGits/hbase-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HbasesGetter has a method to return a HbaseInterface.
// A group's client should implement this interface.
type HbasesGetter interface {
	Hbases(namespace string) HbaseInterface
}

// HbaseInterface has methods to work with Hbase resources.
type HbaseInterface interface {
	Create(ctx context.Context, hbase *v1.Hbase, opts metav1.CreateOptions) (*v1.Hbase, error)
	Update(ctx context.Context, hbase *v1.Hbase, opts metav1.UpdateOptions) (*v1.Hbase, error)
	UpdateStatus(ctx context.Context, hbase *v1.Hbase, opts metav1.UpdateOptions) (*v1.Hbase, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Hbase, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.HbaseList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Hbase, err error)
	HbaseExpansion
}

// hbases implements HbaseInterface
type hbases struct {
	client rest.Interface
	ns     string
}

// newHbases returns a Hbases
func newHbases(c *HbaseV1Client, namespace string) *hbases {
	return &hbases{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hbase, and returns the corresponding hbase object, and an error if there is any.
func (c *hbases) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Hbase, err error) {
	result = &v1.Hbase{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hbases").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Hbases that match those selectors.
func (c *hbases) List(ctx context.Context, opts metav1.ListOptions) (result *v1.HbaseList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.HbaseList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hbases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hbases.
func (c *hbases) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hbases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hbase and creates it.  Returns the server's representation of the hbase, and an error, if there is any.
func (c *hbases) Create(ctx context.Context, hbase *v1.Hbase, opts metav1.CreateOptions) (result *v1.Hbase, err error) {
	result = &v1.Hbase{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hbases").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hbase).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hbase and updates it. Returns the server's representation of the hbase, and an error, if there is any.
func (c *hbases) Update(ctx context.Context, hbase *v1.Hbase, opts metav1.UpdateOptions) (result *v1.Hbase, err error) {
	result = &v1.Hbase{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hbases").
		Name(hbase.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hbase).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *hbases) UpdateStatus(ctx context.Context, hbase *v1.Hbase, opts metav1.UpdateOptions) (result *v1.Hbase, err error) {
	result = &v1.Hbase{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hbases").
		Name(hbase.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hbase).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hbase and deletes it. Returns an error if one occurs.
func (c *hbases) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hbases").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hbases) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hbases").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hbase.
func (c *hbases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Hbase, err error) {
	result = &v1.Hbase{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hbases").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
